verbose: False
job:
  chdir: False # default is False
  env_set: # auto export environment vars
    TIMM_USE_OLD_CACHE: 1
    WANDB_BASE_URL: http://172.16.2.55:8955
  env_copy: []
  config:
    override_dirname:
      kv_sep: "="
      item_sep: ","
      exclude_keys: []
run:
  dir: outputs/${hydra.job.name}/run/${_fname:${now:%m-%d}/${now:%H-%M-%S.%f}_${_or:${exp_name}, ${_no_slash:${hydra.job.override_dirname}}}} 
sweep:
  dir: outputs/${hydra.job.name}/multirun/${_fname:${now:%m-%d}/${now:%H-%M-%S.%f}_${exp_name}}  
  subdir: ${_fname:${hydra.job.num}_${_no_slash:${hydra.job.override_dirname}}}

job_logging:
  version: 1
  formatters:
    simple:
      format: "[%(levelname)s] - %(message)s"
    clean_color:
      format:
        "\n\e[92m[%(levelname)s]: %(asctime)s %(filename)s (%(funcName)s: %(lineno)s)\n\e\
        [0m %(message)s"
      datefmt: "%d/%m %H:%M:%S"
    clean:
      format: "\n[%(levelname)s]: %(asctime)s %(filename)s (%(funcName)s: %(lineno)s)\n %(message)s"
      datefmt: "%d/%m %H:%M:%S"
  handlers:
    console:
      class: logging.StreamHandler
      formatter: clean_color
      stream: ext://sys.stdout
    file:
      class: logging.FileHandler
      formatter: clean
      filename: ${hydra:runtime.output_dir}/${hydra:job.name}.log
  root:
    level: INFO
    handlers: [console, file]
  disable_existing_loggers: false
hydra_logging:
  version: 1
  formatters:
    simple:
      format: "[HYDRA %(levelname)s] - %(message)s"
    clean_color:
      format:
        "\n\e[92m[HYDRA %(levelname)s]: %(asctime)s %(filename)s (%(funcName)s: %(lineno)s)\n\e\
        [0m %(message)s"
      datefmt: "%d/%m %H:%M:%S"
    clean:
      format: "\n[HYDRA %(levelname)s]: %(asctime)s %(filename)s (%(funcName)s: %(lineno)s)\n %(message)s"
      datefmt: "%d/%m %H:%M:%S"
  handlers:
    console:
      class: logging.StreamHandler
      formatter: clean_color
      stream: ext://sys.stdout
  root:
    level: INFO
    handlers: [console]
  disable_existing_loggers: false
