# https://lightning.ai/docs/pytorch/stable/api/lightning.pytorch.callbacks.DeviceStatsMonitor.html

device_stats_monitor:
  _target_: lightning.pytorch.callbacks.DeviceStatsMonitor
  cpu_stats: null # null | True | False