# https://lightning.ai/docs/pytorch/stable/api/lightning.pytorch.callbacks.ModelCheckpoint.html

model_checkpoint:
  _target_: src.utils.callbacks.CustomModelCheckpoint
  dirpath: ${env.output_dir}/fold_${cv.fold_idx}/ckpts # directory to save the model file
  filename: "ep={epoch}_step={step}_${_no_slash:${task.metric}}={${task.metric}:.6f}"  # checkpoint filename
  monitor: ${task.metric} # name of the logged metric which determines when model is improving
  verbose: True # verbosity mode
  save_last: True # additionally always save an exact copy of the last checkpoint to a file last.ckpt
  save_top_k: -1 # save k best models (determined by above metric), -1 for unlimitted
  mode: ${task.metric_mode} # min | max
  auto_insert_metric_name: False # when True, the checkpoints filenames will contain the metric name
  save_weights_only: False # if True, then only the model’s weights will be saved
  every_n_train_steps: null # number of training steps between checkpoints
  train_time_interval: null # checkpoints are monitored at the specified time interval
  every_n_epochs: null # number of epochs between checkpoints
  save_on_train_epoch_end: False # whether to run checkpointing at the end of the training epoch or the end of validation
  enable_version_counter: True